[package]
name = "tecs-winit-host"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false
build = "build.rs"

[dependencies]
anyhow.workspace = true
image.workspace = true
bytemuck.workspace = true
pollster.workspace = true
serde_json.workspace = true
glam.workspace = true
wgpu = { workspace = true, features = ["glsl"] }
winit.workspace = true

[dev-dependencies]
tecs-assets = { path = "../tecs-assets" }
