#!/usr/bin/env python3
"""Renders each module's signatures into its own page with tealdoc.

A module page is prose first and reference second, both on one page. The prose
says why the module is shaped the way it is, which no generator knows. The
reference below it says what each function takes and what comes back, which no
person should be copying by hand: the type checker never reads the docs, so a
parameter that changed name stays wrong until a reader trips over it.

    reference.py          rewrite the reference section of every page below
    reference.py --check  re-render and diff against what is committed

--check is what keeps those sections honest. Without it a page drifts the first
time its module gains a function, and a stale reference is worse than none.

tealdoc comes from the pinned vendor tree, so two machines render the same
bytes. Run `make dev-tools` if it is missing.

Everything from the marker line to the end of a page is generated and is
rewritten wholesale, so edits belong above it. Output goes through prettier
before it lands, because `make format-check` formats these pages like any
other and an unformatted block would fail there instead of here.
"""

import argparse
import pathlib
import re
import shutil
import subprocess
import sys
import tempfile

REPO = pathlib.Path(__file__).resolve().parents[2]
TEALDOC = REPO / "vendor" / "bin" / "tealdoc"

MARKER = "<!-- @generated by docs/scripts/reference.py from {sources}. Do not edit below this line. -->"
MARKER_PATTERN = re.compile(r"^<!-- @generated by docs/scripts/reference\.py .*-->$", re.M)

LEAD = """## Reference

Every function and type this module carries, rendered from {sources}."""

# page -> the sources it renders, each with the name a game writes that source's
# members under.
#
# A class module renders under the class as well as the module, because that is
# how a game reaches it: `tecs.camera.Camera.create`, never `tecs.camera.create`.
# `tecs.audio` and `tecs.data` are the pages with several sources, because each
# is one module to a game and several files here.
#
# A module that sits inside another module has its own page in a directory
# named for the parent, rather than a section of the parent's page. One page per
# module keeps a page the size of the module it documents: the sheet fold into
# `tecs.animation` already produced thirteen hundred lines, and a parent holding
# several of those would produce a page nobody scrolls through. It also keeps
# one source per page, so the name each member is rendered under is the name a
# game writes it as, with nothing to disambiguate.
#
# A page whose module is several modules at one level names them all, in the
# order its prose reads: `tecs.data` is JSON, compression and hashing, and its
# reference section runs the same way.
#
# `tecs.version` is a string and has no source to render, and neither has a
# namespace that carries only other modules: `docs/modules/gfx/index.md` is
# prose and a list of what is under it. `tecs.http` and `tecs.physics` are left
# out on purpose: the first is being rewritten and the second is a stub whose
# module is mid-replacement, so a rendered reference would describe something
# that is about to move. Both come back here when they settle.
MODULES = [
    ("docs/ecs/index.md", [("src/tecs/ecs.tl", "tecs.ecs")]),
    ("docs/modules/animation.md", [("src/tecs/gfx/animation.tl", "tecs.animation")]),
    ("docs/modules/application.md", [("src/tecs/Application.tl", "tecs.application.Application")]),
    ("docs/modules/assets.md", [("src/tecs/assets.tl", "tecs.assets")]),
    (
        "docs/modules/audio.md",
        [("src/tecs/Audio.tl", "tecs.audio.Audio"), ("src/tecs/platform/audio.tl", "tecs.audio")],
    ),
    ("docs/modules/camera.md", [("src/tecs/gfx/Camera.tl", "tecs.camera.Camera")]),
    ("docs/modules/capabilities.md", [("src/tecs/platform/capabilities.tl", "tecs.capabilities")]),
    ("docs/modules/clipboard.md", [("src/tecs/platform/clipboard.tl", "tecs.clipboard")]),
    ("docs/modules/components.md", [("src/tecs/components.tl", "tecs.components")]),
    (
        "docs/modules/data.md",
        [
            ("src/tecs/data.tl", "tecs.data"),
            ("src/tecs/compress.tl", "tecs.data"),
            ("src/tecs/hash.tl", "tecs.data"),
        ],
    ),
    ("docs/modules/events.md", [("src/tecs/platform/events.tl", "tecs.events")]),
    ("docs/modules/filesystem.md", [("src/tecs/platform/filesystem.tl", "tecs.filesystem")]),
    ("docs/modules/future.md", [("src/tecs/Future.tl", "tecs.future.Future")]),
    ("docs/modules/gamepad.md", [("src/tecs/platform/Gamepad.tl", "tecs.gamepad.Gamepad")]),
    ("docs/modules/gfx/layers.md", [("src/tecs/gfx/layers.tl", "tecs.gfx.layers")]),
    ("docs/modules/input.md", [("src/tecs/platform/Input.tl", "tecs.input.Input")]),
    ("docs/modules/log.md", [("src/tecs/log.tl", "tecs.log")]),
    ("docs/modules/materials.md", [("src/tecs/gpu/materials.tl", "tecs.materials")]),
    ("docs/modules/mcp.md", [("src/tecs/mcp/init.tl", "tecs.mcp")]),
    ("docs/modules/net.md", [("src/tecs/net.tl", "tecs.net")]),
    ("docs/modules/particles.md", [("src/tecs/gfx/particles.tl", "tecs.particles")]),
    ("docs/modules/paths.md", [("src/tecs/platform/paths.tl", "tecs.paths")]),
    ("docs/modules/proc.md", [("src/tecs/platform/proc.tl", "tecs.proc")]),
    ("docs/modules/renderer.md", [("src/tecs/Renderer.tl", "tecs.renderer.Renderer")]),
    ("docs/modules/sensors.md", [("src/tecs/platform/sensors.tl", "tecs.sensors")]),
    ("docs/modules/sequence.md", [("src/tecs/sequence/init.tl", "tecs.sequence")]),
    ("docs/modules/system.md", [("src/tecs/platform/system.tl", "tecs.system")]),
    ("docs/modules/text.md", [("src/tecs/gfx/text.tl", "tecs.text")]),
    ("docs/modules/time.md", [("src/tecs/platform/time.tl", "tecs.time")]),
    ("docs/modules/watch.md", [("src/tecs/platform/watch.tl", "tecs.watch")]),
    ("docs/modules/window.md", [("src/tecs/platform/Window.tl", "tecs.window.Window")]),
    ("docs/modules/workers.md", [("src/tecs/workers.tl", "tecs.workers")]),
]

ANCHOR = re.compile(r'^<a id="(.+)"></a>$')


def moduleName(source: str) -> str:
    """The name tealdoc gives a file, which is its path under `src`."""
    return source[len("src/") :].removesuffix(".tl").replace("/", ".")


def escapeBraces(line: str) -> str:
    """Wraps a bare `{{` in prose so Vue reads it as two characters.

    A page is compiled as a Vue template, so `{{ ... }}` outside a code element
    is an interpolation, and a doc comment writing `{{"name", "type"}}` in plain
    words fails the build outright: Vue looks for the closing `}}` and reaches
    the end of the page without finding one. tealdoc marks everything it emits
    as code `v-pre` itself; this is for the author's own words around it, which
    it must not rewrite.
    """
    out = []
    code = False
    rest = line
    while rest:
        if rest[0] == "`":
            code = not code
            out.append("`")
            rest = rest[1:]
        elif not code and rest.startswith("{{"):
            out.append("<span v-pre>{{</span>")
            rest = rest[2:]
        else:
            out.append(rest[0])
            rest = rest[1:]
    return "".join(out)


def render(source: str, public: str, scratch: pathlib.Path) -> str:
    """tealdoc's output for one source file, as one part of a page's section."""
    raw = scratch / "raw.md"
    subprocess.run(
        [str(TEALDOC), "md", "--no-warn-missing", "-o", str(raw), source],
        cwd=REPO,
        check=True,
        stdout=subprocess.DEVNULL,
    )
    module = moduleName(source)

    # Split into one block per documented item. Every block starts with the
    # item's anchor, and what comes before the first anchor is tealdoc's own
    # module heading, which the page already has as its title.
    blocks: list[tuple[str, list[str]]] = []
    current: list[str] = []
    name = ""
    for line in raw.read_text().splitlines():
        match = ANCHOR.match(line)
        if match:
            if current:
                blocks.append((name, current))
            name, current = match.group(1), [line]
        elif current:
            current.append(line)

    if current:
        blocks.append((name, current))

    kept: list[str] = []
    for name, block in blocks:
        if name in (module, "$" + module):
            continue
        # A `_`-prefixed field is private. tealdoc emits it either way, and a
        # reference that names one is inviting a game to write to it.
        member = name[len(module) + 1 :] if name.startswith(module + ".") else name
        if any(part.startswith("_") for part in member.split(".")):
            continue
        kept.extend(block)

    body = "\n".join(kept)
    body = body.replace(module + ".", public + ".")
    # One `##` per item floods a page's outline, so items sit under the section
    # heading rather than beside it. Their parameter and return tables are
    # already `####`, which lands under them.
    body = re.sub(r"^## ", "### ", body, flags=re.M)
    body = "\n".join(escapeBraces(line) for line in body.splitlines())
    return body.strip("\n")


def sentence(sources: list[str]) -> str:
    """The sources a page renders, named the way prose names a short list."""
    quoted = ["`%s`" % source for source in sources]
    if len(quoted) == 1:
        return quoted[0]
    return "%s and %s" % (", ".join(quoted[:-1]), quoted[-1])


def compose(page: pathlib.Path, sources: list[tuple[str, str]], scratch: pathlib.Path) -> str:
    """The whole page: whatever is above the marker, then a fresh render."""
    text = page.read_text()
    match = MARKER_PATTERN.search(text)
    prose = text[: match.start()] if match else text
    named = sentence([source for source, _ in sources])
    body = "\n\n".join(render(source, public, scratch) for source, public in sources)
    return "%s\n%s\n\n%s\n\n%s\n" % (
        prose.rstrip("\n"),
        MARKER.format(sources=", ".join(source for source, _ in sources)),
        LEAD.format(sources=named),
        body,
    )


def prettify(path: pathlib.Path) -> None:
    subprocess.run(
        ["prettier", "--write", "--log-level", "warn", "--config", str(REPO / ".prettierrc"), str(path)],
        cwd=REPO,
        check=True,
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="re-render and diff; write nothing")
    args = parser.parse_args()

    if not TEALDOC.is_file():
        print("tealdoc is not in vendor/bin; run 'make dev-tools'", file=sys.stderr)
        return 1

    stale = []
    with tempfile.TemporaryDirectory(prefix="tecs-reference.") as directory:
        scratch = pathlib.Path(directory)
        for relative, sources in MODULES:
            page = REPO / relative
            composed = compose(page, sources, scratch)
            if args.check:
                candidate = scratch / pathlib.Path(relative).name
                candidate.write_text(composed)
                prettify(candidate)
                if candidate.read_text() != page.read_text():
                    stale.append(relative)
            else:
                page.write_text(composed)
                prettify(page)

    if args.check:
        if stale:
            print("Module pages are stale against their sources:", file=sys.stderr)
            for relative in stale:
                print("  " + relative, file=sys.stderr)
            print("\nRun docs/scripts/reference.py to regenerate them.", file=sys.stderr)
            return 1
        print("OK: every module page matches a fresh render")
        return 0

    print("wrote the reference section of %d pages" % len(MODULES))
    return 0


if __name__ == "__main__":
    sys.exit(main())
