#!/usr/bin/env bash
#
# Renders the public API of `src/tecs/init.tl` and `src/tecs/ecs.tl` with
# tealdoc and writes it to docs/modules/reference.md.
#
# The signatures on that page are generated because a hand-written signature is
# a copy that goes stale silently: the type-checker never reads the docs, so a
# parameter that changed name stays wrong until a reader trips over it. The
# prose pages beside it are not generated and are not replaced by it; they say
# why a module is shaped the way it is, which no generator knows.
#
#   reference.sh          write docs/modules/reference.md
#   reference.sh --check  re-render and diff against what is committed
#
# --check is what keeps the committed page honest. Without it the page drifts
# the first time `init.tl` gains a field, and a stale reference is worse than
# none.
#
# tealdoc comes from the pinned vendor tree, so two machines render the same
# bytes. Run `make dev-tools` if it is missing.
#
# Only those two files are rendered, and that is a limit rather than a
# preference. tealdoc renders a colon method by inserting `self` as an unnamed
# first parameter, which shifts every name after it: `function
# Camera:matrix(width: number, height: number)` comes out as `matrix(width:
# Camera, height: number, number)`. Every parameter name in it is wrong. It
# also emits `_`-prefixed fields. Both of these declare their functions as
# record fields and have no methods and no private fields, so none of that
# reaches this page; a module page would be full of it, and a confidently
# wrong signature is worse than none.
set -euo pipefail

here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo=$(CDPATH= cd -- "$here/../.." && pwd)
tealdoc="$repo/vendor/bin/tealdoc"
sources=(src/tecs/init.tl src/tecs/ecs.tl)
page="$repo/docs/modules/reference.md"

if [ ! -x "$tealdoc" ]; then
    echo "tealdoc is not in vendor/bin; run 'make dev-tools'" >&2
    exit 1
fi

scratch=$(mktemp -d "${TMPDIR:-/tmp}/tecs-reference.XXXXXX")
trap 'rm -rf "$scratch"' EXIT HUP INT TERM

# --no-warn-missing rather than --all. Every public field is emitted either
# way; what `--all` adds is a file's own locals, `ENGINE` and `CLASSES` and
# `globals` and the private requires, which are not public and would read as if
# they were. The warnings it silences are about the module fields, whose
# documentation is the module page each of them links to.
(cd "$repo" && "$tealdoc" md --no-warn-missing -o "$scratch/raw.md" "${sources[@]}" >/dev/null)

# The marker on the second line is read by scripts/format.py, which leaves a
# file alone once it says a tool wrote it, and by anyone about to edit this by
# hand.
{
    cat <<'PREAMBLE'
---
# @generated by docs/scripts/reference.sh. Do not edit.
description: "Generated signatures for every value and type the tecs module exports, rendered from src/tecs/init.tl"
outline: [2, 2]
---

# Generated reference

Every value and type `tecs` carries, rendered from `src/tecs/init.tl` and `src/tecs/ecs.tl` by
[tealdoc](https://github.com/teal-language/tealdoc). Signatures, doc comments, parameters and returns, checked
against a fresh render so it cannot drift from the code. The modules come first, alphabetically, and everything
under `tecs.ecs` follows.

This is a reference, not an explanation. The pages in the [module index](/modules/) say why each module is shaped
the way it is, which is the part a generator does not know; read those first and come here for the exact spelling.

The `tecs.` prefix below is what a game writes. Every module but `tecs.ecs` resolves on first access, so reading
one loads it and requiring `tecs` does not.

PREAMBLE
    # tealdoc names the module by its file, `tecs.init`. A game writes
    # `tecs.ecs.newWorld`, never `tecs.init.newWorld`, so the prefix is rewritten
    # here rather than left to mislead. The module heading and its anchor go
    # with it, since the preamble already says what the page is.
    #
    # Tealdoc writes signatures as raw HTML code blocks so it can put links
    # inside them. The site wants actual Markdown fences: they get Teal syntax
    # highlighting, keep braces away from Vue interpolation, and remain useful
    # when the page is read as plain Markdown. The awk below changes each
    # signature to a `teal` fence, drops links that cannot exist inside a code
    # fence, and decodes the HTML entities tealdoc escaped for its old block.
    #
    # Prose still needs the `v-pre` guard. The `@param` on `newFFIEvent` writes
    # `{{"name", "type"}, ...}` in plain words, which Vue otherwise reads as
    # an interpolation. Backtick spans already receive the same protection
    # from the site's Markdown rule, so only bare braces are wrapped here.
    sed -e '/^<a id="\$tecs\.ecs"><\/a>$/d' \
        -e '/^<a id="tecs\.ecs"><\/a>$/d' \
        -e 's/^# Module: tecs\.ecs$/## The ECS, in full/' \
        -e 's/tecs\.init\./tecs./g' \
        -e '/^<a id="\$tecs\.init"><\/a>$/d' \
        -e '/^<a id="tecs\.init"><\/a>$/d' \
        -e '/^# Module: tecs\.init$/d' \
        "$scratch/raw.md" |
        awk '
            function signature(line) {
                gsub(/<[^>]+>/, "", line)
                gsub(/&lt;/, "<", line)
                gsub(/&gt;/, ">", line)
                gsub(/&quot;/, "\"", line)
                gsub(/&#39;/, sprintf("%c", 39), line)
                gsub(/&amp;/, sprintf("%c", 38), line)
                if (length(line) > 0) {
                    print line
                }
            }
            /^<pre><code[^>]*>/ {
                in_signature = 1
                sub(/^<pre><code[^>]*>/, "")
                print "```teal"
                signature($0)
                next
            }
            in_signature && /^<\/code><\/pre>$/ {
                print "```"
                in_signature = 0
                next
            }
            in_signature {
                signature($0)
                next
            }
            {
                out = ""
                code = 0
                rest = $0
                while (length(rest) > 0) {
                    head = substr(rest, 1, 1)
                    pair = substr(rest, 1, 2)
                    if (head == "`") {
                        code = !code
                        out = out head
                        rest = substr(rest, 2)
                    } else if (!code && pair == "{{") {
                        out = out "<span v-pre>{{</span>"
                        rest = substr(rest, 3)
                    } else {
                        out = out head
                        rest = substr(rest, 2)
                    }
                }
                print out
            }
        '
} >"$scratch/page.md"

if [ "${1:-}" = "--check" ]; then
    if ! diff -u "$page" "$scratch/page.md" >"$scratch/diff" 2>&1; then
        echo "docs/modules/reference.md is stale against src/tecs/init.tl:" >&2
        cat "$scratch/diff" >&2
        echo >&2
        echo "Run docs/scripts/reference.sh to regenerate it." >&2
        exit 1
    fi
    echo "OK: docs/modules/reference.md matches a fresh render"
    exit 0
fi

cp "$scratch/page.md" "$page"
echo "wrote docs/modules/reference.md"
