[package]
name = "tecs-build-support"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
clap.workspace = true
anyhow.workspace = true
regex.workspace = true
serde_json.workspace = true
sha2.workspace = true
flate2.workspace = true
tar = "0.4"
toml.workspace = true
tempfile.workspace = true
walkdir.workspace = true
