"""Formats every language in the tree that has a formatter worth running.

One description of what gets formatted and by what, so the Makefile and CMake
both call this rather than each carrying a copy of the file list.

Files come from `git ls-files`, which is how nothing ignored is ever reached:
the ignore rules are already written down in .gitignore and this does not get a
second opinion. On top of that, generated and third-party trees are named in
EXCLUDED, and a file announcing itself as generated in its opening lines is
skipped wherever it sits.

GLSL deliberately has no formatter. clang-format has no GLSL mode and reads an
interface block as a class definition, so `layout(...) uniform View { ... }
view;` comes back with `view;` stranded on a line of its own. glslx 0.3.1 reads
the WebGL dialect, where `flat`, `switch` and a `u`-suffixed integer literal do
not exist, and its formatter returns such a file unchanged without saying so.
See STYLE.md.
"""

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# Trees this repository carries but did not write, and data a tool emits.
# Reformatting either produces a diff against upstream that has to be
# reapplied by hand every time it is updated.
EXCLUDED = (
    "vendor/",  # third-party sources, vendored verbatim
    "assets/fonts/",  # font metrics, emitted by the atlas generator
    "benches/cross-engine/assets/",  # sprite atlas, emitted by Aseprite
    "scripts/__pycache__/",
)

# What a generated file says about itself in its first few lines. The build
# writes some of these into the source tree, so the marker is the check rather
# than a path list that would go stale.
GENERATED_MARKERS = ("generated by", "@generated", "do not edit")
GENERATED_SCAN_LINES = 5

# suffix or exact name -> the language key it formats as. Prettier owns the web
# side, and it is declared out to the whole set it handles rather than to the
# suffixes present today, so a documentation site landing here is formatted the
# day it arrives instead of the day someone remembers this file.
SUFFIXES = {
    ".c": "c",
    ".h": "c",
    ".lua": "lua",
    ".tl": "teal",
    ".py": "python",
    ".cmake": "cmake",
    ".json": "prettier",
    ".jsonc": "prettier",
    ".js": "prettier",
    ".jsx": "prettier",
    ".mjs": "prettier",
    ".cjs": "prettier",
    ".ts": "prettier",
    ".tsx": "prettier",
    ".mts": "prettier",
    ".cts": "prettier",
    ".vue": "prettier",
    ".css": "prettier",
    ".scss": "prettier",
    ".html": "prettier",
    ".md": "prettier",
    ".yml": "prettier",
    ".yaml": "prettier",
}
NAMES = {"CMakeLists.txt": "cmake"}

# language -> (tool, apply argv, check argv). The tool is named separately so a
# missing one is reported as itself rather than as whatever the shell said.
TOOLS = {
    "c": ("clang-format", ["clang-format", "-i"], ["clang-format", "--dry-run", "--Werror"]),
    "lua": ("stylua", ["stylua"], ["stylua", "--check"]),
    "teal": (
        "vendor/bin/ceru",
        ["vendor/bin/ceru"],
        ["vendor/bin/ceru", "--check"],
    ),
    "python": ("ruff", ["ruff", "format", "-q"], ["ruff", "format", "-q", "--check"]),
    "cmake": ("gersemi", ["gersemi", "-i"], ["gersemi", "--check"]),
    "prettier": (
        "prettier",
        ["prettier", "--write", "--log-level", "warn"],
        ["prettier", "--check", "--log-level", "warn"],
    ),
}


def isGenerated(path):
    """True when a file's opening lines say a tool wrote it."""
    try:
        with path.open("r", encoding="utf-8", errors="ignore") as handle:
            for _ in range(GENERATED_SCAN_LINES):
                line = handle.readline()
                if not line:
                    break
                lowered = line.lower()
                if any(marker in lowered for marker in GENERATED_MARKERS):
                    return True
    except OSError:
        return False
    return False


def collect(paths):
    """Tracked files under `paths`, grouped by language."""
    argv = ["git", "-C", str(REPO), "ls-files", "-z", "--"] + list(paths)
    listing = subprocess.run(argv, capture_output=True, text=True, check=True)

    grouped = {}
    for name in listing.stdout.split("\0"):
        if not name or name.startswith(EXCLUDED):
            continue
        path = REPO / name
        language = NAMES.get(path.name) or SUFFIXES.get(path.suffix)
        if not language or not path.is_file():
            continue
        if isGenerated(path):
            continue
        grouped.setdefault(language, []).append(name)
    return grouped


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="report what would change; write nothing")
    parser.add_argument("paths", nargs="*", default=["."], help="limit to these paths (default: the whole tree)")
    args = parser.parse_args()

    grouped = collect(args.paths or ["."])
    missing = sorted({TOOLS[lang][0] for lang in grouped if not shutil.which(TOOLS[lang][0])})
    if missing:
        sys.exit(f"formatters not installed: {', '.join(missing)}. Run `make deps`.")

    failed = []
    for language in sorted(grouped):
        _, apply, check = TOOLS[language]
        argv = (check if args.check else apply) + sorted(grouped[language])
        if subprocess.run(argv, cwd=REPO).returncode != 0:
            failed.append(language)

    if failed:
        what = "not formatted" if args.check else "failed to format"
        sys.exit(f"{what}: {', '.join(failed)}")


if __name__ == "__main__":
    main()
