"""Packs the content root into a C array, so one executable carries everything.

A `tecs` built as a single file has no directory beside it: no compiled Lua, no
Teal type information, no shaders, no fonts, no templates, no license notices.
This deflates all of it into one stream and emits it as a C source file the
build compiles in.

**Deflate rather than bytecode.** LuaJIT can embed bytecode and nothing here
does, for three reasons. Bytecode is tied to the word size, the endianness and
the LuaJIT build, so one payload becomes one payload per target, and the CLI
has to be able to write the engine's Lua into a game package for the platform it
is packaging on. The saving is small, because bytecode is about the size of
deflated source and its win is load time, which is paid once at process start.
And source is what the content watcher reloads, which is a first-class feature
here rather than a debugging aid.

**One stream over the whole archive, not one per entry.** The payload is read
whole exactly once, when it is unpacked, so per-entry framing would buy random
access nothing asks for and cost the ratio: 2.5 MB of Teal sources compress far
better as one stream than as six hundred.

The format is deliberately dull, because `cli/payload.c` has to parse it with no
allocator to speak of and no library beyond zlib:

```
 Field                Bytes  Note
 ───────────────────  ─────  ────────────────────────────────
 magic                8      TECSPAY1
 count                4      little-endian
 per entry: name len  2
            name      n      forward slashes, relative
            data len  4
            data      n
```
"""

import argparse
import hashlib
import struct
import sys
import zlib
from pathlib import Path

MAGIC = b"TECSPAY1"

# What never goes in. Each is output of a build step that produced something
# else already in the payload, or a tree the payload has no use for.
SKIP_SUFFIXES = (".o", ".obj", ".d", ".pyc")
SKIP_NAMES = (".DS_Store",)


def collect(roots):
    """Every file under each (prefix, directory) pair, as (name, bytes)."""
    entries = []
    for prefix, directory in roots:
        base = Path(directory)
        if not base.is_dir():
            sys.exit(f"tecs: {base} is not there, so it cannot be packed")
        for path in sorted(base.rglob("*")):
            if not path.is_file():
                continue
            if path.name in SKIP_NAMES or path.suffix in SKIP_SUFFIXES:
                continue
            relative = path.relative_to(base).as_posix()
            name = f"{prefix}/{relative}" if prefix else relative
            entries.append((name, path.read_bytes()))
    return entries


def pack(entries):
    """The archive, before compression."""
    out = bytearray(MAGIC)
    out += struct.pack("<I", len(entries))
    for name, data in entries:
        encoded = name.encode("utf-8")
        out += struct.pack("<H", len(encoded))
        out += encoded
        out += struct.pack("<I", len(data))
        out += data
    return bytes(out)


def render(compressed, plainLength, identity):
    """The C source. A plain array, because a string literal has a length limit
    every compiler sets differently and this is measured in megabytes."""
    lines = [
        "/* Generated by scripts/genpayload.py. Do not edit.",
        " *",
        " * The whole content root, deflated. cli/payload.c inflates it once at",
        " * startup and hands it to Lua, which writes it out beside the cache",
        " * directory named after the identity below.",
        " */",
        "",
        "#include <stddef.h>",
        "",
        f'const char tecsPayloadIdentity[] = "{identity}";',
        f"const size_t tecsPayloadPlainSize = {plainLength}u;",
        f"const size_t tecsPayloadSize = {len(compressed)}u;",
        "const unsigned char tecsPayload[] = {",
    ]

    for start in range(0, len(compressed), 20):
        chunk = compressed[start : start + 20]
        lines.append("    " + "".join(f"0x{byte:02x}," for byte in chunk))

    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        action="append",
        default=[],
        metavar="PREFIX=DIRECTORY",
        help="a directory to pack, under PREFIX. Repeatable; an empty PREFIX packs at the top.",
    )
    parser.add_argument("--out", required=True, help="the C source to write")
    args = parser.parse_args()

    roots = []
    for pair in args.root:
        prefix, _, directory = pair.partition("=")
        roots.append((prefix, directory))

    entries = collect(roots)
    plain = pack(entries)

    # The identity is over the uncompressed archive, so two builds of the same
    # tree share a cache directory whatever the compressor did, and a changed
    # engine never reuses the last one's unpacked copy.
    identity = hashlib.sha256(plain).hexdigest()[:16]
    compressed = zlib.compress(plain, 9)

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(compressed, len(plain), identity), encoding="utf-8")

    print(
        f"payload: {len(entries)} files, {len(plain) / 1048576:.2f} MB "
        f"deflated to {len(compressed) / 1048576:.2f} MB ({identity})"
    )


if __name__ == "__main__":
    main()
