#!/usr/bin/env python3
"""Generate a static function-pointer table for a native library.

`ffi.load` needs a shared object and a working `dlopen`. iOS has neither: every
library is linked into the executable, and loading one by name at runtime is
not permitted. A target like that can still call C, but the addresses have to
be taken at build time rather than looked up at run time.

So for each library this emits a struct of typed function pointers, one C file
that fills it by taking the address of each function, and a cdef the FFI reads
it back through. The engine then calls through the struct instead of through a
handle it had to resolve, and the same code path works whether the library was
linked statically or loaded dynamically.

Signatures are transformed from the generated cdef rather than parsed again, so
the pointer table cannot disagree with the bindings.
"""

import argparse
import re
import sys
from pathlib import Path

# Splits a declaration into its leading type, the function name, and its
# parameter list. The name is the last identifier before the opening paren.
SIGNATURE_RE = re.compile(r"^(.*?)(\b\w+)\s*\((.*)\)$", re.S)

# Statements that are not function declarations, whatever else they look like.
NOT_A_FUNCTION = ("typedef", "struct", "union", "enum", "static", "extern \"C\"")


def statements(cdef: str):
    """Yields top-level statements, so a struct body's semicolons are ignored."""
    depth = 0
    current = []
    for character in cdef:
        if character == "{":
            depth += 1
        elif character == "}":
            depth -= 1
        elif character == ";" and depth == 0:
            yield "".join(current)
            current = []
            continue
        current.append(character)


def readCdef(path: Path) -> str:
    text = path.read_text()
    start = text.index("[==========[") + len("[==========[")
    end = text.rindex("]==========]")
    return text[start:end]


def declarations(cdef: str, prefix: str):
    """Yields (returnType, name, params) for every exported function."""
    seen = set()
    for statement in statements(cdef):
        body = " ".join(statement.split())

        # Declaration keywords vary by library: SDL spells them with `extern`,
        # Box2D with a macro that expands to nothing. Matching the shape rather
        # than a keyword covers both.
        if not body or body.startswith(NOT_A_FUNCTION):
            continue
        body = body.removeprefix("extern ").strip()

        signature = SIGNATURE_RE.match(body)
        if not signature:
            continue

        returnType, name, params = signature.groups()
        returnType = returnType.strip()
        params = params.strip()

        # Only the library's own surface. A header that pulls in another
        # library's declarations would otherwise put symbols in this table that
        # this library does not define.
        if prefix and not name.startswith(prefix):
            continue
        if name in seen:
            continue

        # A function returning a function pointer cannot be spelled as a
        # struct member by wrapping the name, and none are called from here.
        # A function-pointer typedef reaches here looking like a declaration
        # and is rejected the same way.
        if "(*" in returnType or "(" in returnType:
            continue
        if not returnType or not name.isidentifier():
            continue

        seen.add(name)
        yield returnType, name, params


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--cdef", required=True, help="generated cdef .lua")
    parser.add_argument("--name", required=True, help="library key, e.g. sdl3")
    parser.add_argument("--struct", required=True, help="C struct name")
    parser.add_argument("--prefix", default="", help="only export this prefix")
    parser.add_argument("--header", action="append", required=True)
    parser.add_argument("--source-out", required=True)
    parser.add_argument("--cdef-out", required=True)
    args = parser.parse_args()

    cdef = readCdef(Path(args.cdef))
    functions = list(declarations(cdef, args.prefix))
    if not functions:
        sys.exit(f"no exported functions found for {args.name}")

    members = []
    initialisers = []
    for returnType, name, params in functions:
        pointer = f"{returnType} (*{name})({params});"
        members.append(f"    {pointer}")
        initialisers.append(f"    .{name} = {name},")

    struct = args.struct
    body = "\n".join(members)

    header = "\n".join(f"#include <{h}>" for h in args.header)
    source = f"""/* Generated by scripts/genregistry.py. Do not edit.
 *
 * Addresses are taken here, at build time, because a target that forbids
 * loading a library by name at run time can still link one. See the generator
 * for why that is the case that decides this design.
 */

{header}

typedef struct {struct} {{
{body}
}} {struct};

static const {struct} api = {{
{chr(10).join(initialisers)}
}};

/* Returned untyped so the registry stays one shape regardless of which
 * libraries a target links. Lua casts it back using the cdef beside it. */
const void *tecs_{args.name}_api(void)
{{
    return &api;
}}
"""

    luaCdef = f"""-- Generated by scripts/genregistry.py. Do not edit.
-- Function-pointer table for {args.name}, filled at build time.
return [==========[
typedef struct {struct} {{
{body}
}} {struct};
]==========]
"""

    Path(args.source_out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.cdef_out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.source_out).write_text(source)
    Path(args.cdef_out).write_text(luaCdef)
    print(f"{args.source_out}: {len(functions)} functions")


if __name__ == "__main__":
    main()
