"""Writes the toolchain table the `tecs` binary carries.

Two things a running `tecs` has to know and cannot work out for itself.

**What gets formatted and by what.** That is described once, in
`scripts/format.py`, which the repository's own `make format` runs. A user's
machine has this repository nowhere on it, so the CLI cannot run that script;
it reads the table this emits instead. The table is taken by importing
`format.py` rather than by restating it, so the two cannot disagree. If they
could, an editor formatting on save and a CI job checking formatting would one
day answer differently about the same file, and the diff would be nobody's.

**Which revision of the type checker and the formatter is inside the binary.**
Both are pinned to commits in `cmake/Revisions.cmake` and both are compiled in,
so `tecs check` and `tecs format` run the same two programs this tree is
checked and formatted by. `tecs info` prints them, because a version that
cannot be read is a pin nobody can verify.
"""

import argparse
import importlib.util
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent


def loadFormatTables():
    """The tables from format.py, imported rather than re-read."""
    spec = importlib.util.spec_from_file_location("tecsformat", REPO / "scripts" / "format.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.describe()


def quote(text):
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def render(value, indent):
    """A Lua literal for a JSON-shaped value."""
    pad = "    " * indent
    inner = "    " * (indent + 1)
    if value is None:
        return "nil"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        return quote(value)
    if isinstance(value, list):
        if not value:
            return "{}"
        items = ",\n".join(inner + render(item, indent + 1) for item in value)
        return "{\n" + items + ",\n" + pad + "}"
    if isinstance(value, dict):
        if not value:
            return "{}"
        rows = []
        for key in sorted(value):
            entry = value[key]
            if entry is None:
                continue
            rows.append(f"{inner}[{quote(key)}] = {render(entry, indent + 1)}")
        return "{\n" + ",\n".join(rows) + ",\n" + pad + "}"
    raise TypeError(f"cannot render {type(value)!r}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--teal-ref", required=True, help="the Teal commit this binary carries")
    parser.add_argument("--cerulean-ref", required=True, help="the Cerulean commit this binary carries")
    parser.add_argument("--out", required=True, help="where to write the Lua module")
    args = parser.parse_args()

    table = {
        "format": loadFormatTables(),
        "pins": {"teal": args.teal_ref, "cerulean": args.cerulean_ref},
    }

    body = [
        "-- Generated by scripts/gentooling.py. Do not edit.",
        "--",
        "-- The formatting table comes from scripts/format.py, which is the one",
        "-- description of what this tree formats and by what. The pins come from",
        "-- cmake/Revisions.cmake.",
        "return " + render(table, 0),
        "",
    ]

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(body), encoding="utf-8")


if __name__ == "__main__":
    sys.exit(main())
