use std::collections::{BTreeMap, BTreeSet, HashMap, HashSet};
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, Result};
use regex::Regex;
use tempfile::tempdir;

const DROP_TOKENS: &[&str] = &[
    "__extension__",
    "__restrict__",
    "__restrict",
    "__inline__",
    "__inline",
    "__signed__",
    "__nonnull",
    "_Noreturn",
    "SDLCALL",
];
const PROBE_NAME: &str = "tecsconsts";
const LUA_EXACT_INTEGER: u64 = 1_u64 << 53;

#[derive(Debug)]
pub struct Options<'a> {
    pub compiler: &'a str,
    pub headers: &'a [String],
    pub include_directories: &'a [PathBuf],
    pub defines: &'a [String],
    pub keeps: &'a [String],
    pub needed: &'a [String],
    pub define_prefixes: &'a [String],
    pub constants_output: Option<&'a Path>,
    pub output: &'a Path,
}

pub fn generate(options: &Options<'_>) -> Result<()> {
    if let Some(output) = options.constants_output {
        let constants = extract_defines(options)?;
        let mut lines = vec![
            "-- Generated by `cargo xtask`. Do not edit.".to_owned(),
            "return {".to_owned(),
        ];
        for (name, value) in &constants {
            lines.push(format!("    {name} = {},", value.lua()));
        }
        lines.push("}".to_owned());
        write(output, &(lines.join("\n") + "\n"))?;
        println!("{}: {} constants", output.display(), constants.len());
    }

    let preprocessed = preprocess(options, false)?;
    let mut body = clean(&select_by_file(&preprocessed, options.keeps, true))?;
    if !options.needed.is_empty() {
        let mut declared = HashSet::new();
        for statement in statements(&body) {
            declared.extend(declared_names(&statement)?);
        }
        let rejected = clean(&select_by_file(&preprocessed, options.keeps, false))?;
        let prelude = recover_types(&rejected, &declared, options.needed)?;
        let mut available = declared;
        available.extend(identifiers(&prelude)?);
        let missing: Vec<_> = options
            .needed
            .iter()
            .filter(|name| {
                name.split_whitespace()
                    .last()
                    .is_some_and(|name| !available.contains(name))
            })
            .collect();
        if !missing.is_empty() {
            anyhow::bail!(
                "cannot recover declarations for: {}",
                missing
                    .into_iter()
                    .map(|value| value.as_str())
                    .collect::<Vec<_>>()
                    .join(", ")
            );
        }
        body = prelude + &body;
    }

    let contents = if options.output.extension().and_then(|value| value.to_str()) == Some("lua") {
        format!(
            "-- Generated by `cargo xtask`. Do not edit.\n\
             -- headers: {}\n\
             return [==========[\n{}]==========]\n",
            options.headers.join(" "),
            body
        )
    } else {
        body.clone()
    };
    write(options.output, &contents)?;
    println!(
        "{}: {} lines",
        options.output.display(),
        body.lines().count()
    );
    Ok(())
}

#[derive(Clone, Debug, Eq, PartialEq)]
enum Constant {
    Integer(i64),
    Unsigned(u64),
    Float(String),
    String(String),
}

impl Constant {
    fn lua(&self) -> String {
        match self {
            // LuaJIT's LL suffix preserves integers that its default double
            // literal would round.
            Self::Integer(value) if value.unsigned_abs() <= LUA_EXACT_INTEGER => value.to_string(),
            Self::Integer(value) => format!("{value}LL"),
            Self::Unsigned(value) if *value <= LUA_EXACT_INTEGER => value.to_string(),
            Self::Unsigned(value) => format!("{value}ULL"),
            Self::Float(value) => value.clone(),
            Self::String(value) => format!(
                "\"{}\"",
                value
                    .replace('\\', "\\\\")
                    .replace('"', "\\\"")
                    .replace('\n', "\\n")
                    .replace('\r', "\\r")
            ),
        }
    }
}

fn preprocess(options: &Options<'_>, macros: bool) -> Result<String> {
    let directory = tempdir()?;
    let source = directory.path().join("tecsheaders.c");
    fs::write(
        &source,
        options
            .headers
            .iter()
            .map(|header| format!("#include <{header}>"))
            .collect::<Vec<_>>()
            .join("\n")
            + "\n",
    )?;
    let mut command = Command::new(options.compiler);
    command.args(["-E"]);
    if macros {
        command.arg("-dM");
    }
    command.arg("-std=c99");
    add_compiler_options(&mut command, options);
    command.arg(&source);
    output(&mut command, "preprocessor")
}

fn add_compiler_options(command: &mut Command, options: &Options<'_>) {
    for directory in options.include_directories {
        command.arg("-I").arg(directory);
    }
    for define in options.defines {
        command.arg("-D").arg(define);
    }
}

fn output(command: &mut Command, what: &str) -> Result<String> {
    let output = command
        .output()
        .with_context(|| format!("failed to start {what}"))?;
    if !output.status.success() {
        anyhow::bail!(
            "{what} failed ({}):\n{}",
            output.status,
            String::from_utf8_lossy(&output.stderr)
        );
    }
    String::from_utf8(output.stdout).with_context(|| format!("{what} emitted non-UTF-8 output"))
}

fn select_by_file(preprocessed: &str, keeps: &[String], wanted: bool) -> String {
    let marker = Regex::new(r#"^#\s+\d+\s+"([^"]*)""#).expect("static regex");
    let mut active = false;
    let mut lines = Vec::new();
    for line in preprocessed.lines() {
        if let Some(found) = marker.captures(line) {
            active = keeps.iter().any(|keep| found[1].contains(keep)) == wanted;
        } else if active {
            lines.push(line);
        }
    }
    lines.join("\n")
}

fn clean(source: &str) -> Result<String> {
    let attribute = Regex::new(r"__attribute__\s*\(")?;
    let assembly = Regex::new(r"__asm(__)?\s*\(")?;
    let mut text = strip_balanced(source, &attribute);
    text = strip_balanced(&text, &assembly);
    for token in DROP_TOKENS {
        text = Regex::new(&format!(r"\b{}\b", regex::escape(token)))?
            .replace_all(&text, " ")
            .into_owned();
    }
    text = Regex::new(r#"\bextern\s+"C"\s*\{"#)?
        .replace_all(&text, "")
        .into_owned();

    let static_line = Regex::new(r"^\s*static\b")?;
    let assert_line = Regex::new(r"^\s*(_Static_assert|static_assert)\b")?;
    let empty_line =
        Regex::new(r#"^\s*(_Static_assert|static_assert|#pragma|extern\s+"C"|\})?\s*$"#)?;
    let mut lines = Vec::new();
    let mut skipping = false;
    let mut skip_depth = 0_i32;
    for line in text.lines() {
        let stripped = line.trim();
        if !skipping && static_line.is_match(line) {
            skipping = true;
            skip_depth = 0;
        }
        if skipping {
            skip_depth += count(stripped, '{') - count(stripped, '}');
            if skip_depth <= 0 && (stripped.ends_with(';') || stripped.ends_with('}')) {
                skipping = false;
            }
            continue;
        }
        if (empty_line.is_match(line) && !stripped.starts_with('}'))
            || assert_line.is_match(line)
            || stripped.starts_with('#')
        {
            continue;
        }
        lines.push(line.trim_end());
    }
    let text = Regex::new(r"\n{3,}")?
        .replace_all(&lines.join("\n"), "\n\n")
        .trim()
        .to_owned();
    Ok(text + "\n")
}

fn strip_balanced(source: &str, pattern: &Regex) -> String {
    let mut text = source.to_owned();
    while let Some(found) = pattern.find(&text) {
        let opening = found.end() - 1;
        let mut depth = 0_i32;
        let mut closing = None;
        for (offset, character) in text[opening..].char_indices() {
            match character {
                '(' => depth += 1,
                ')' => {
                    depth -= 1;
                    if depth == 0 {
                        closing = Some(opening + offset);
                        break;
                    }
                }
                _ => {}
            }
        }
        let Some(closing) = closing else {
            text.truncate(found.start());
            break;
        };
        text.replace_range(found.start()..=closing, "");
    }
    text
}

fn count(value: &str, character: char) -> i32 {
    value
        .chars()
        .filter(|candidate| *candidate == character)
        .count() as i32
}

fn statements(source: &str) -> Vec<String> {
    let mut depth = 0_i32;
    let mut current = String::new();
    let mut output = Vec::new();
    for character in source.chars() {
        match character {
            '{' => depth += 1,
            '}' => depth -= 1,
            ';' if depth == 0 => {
                current.push(';');
                output.push(std::mem::take(&mut current).trim().to_owned());
                continue;
            }
            _ => {}
        }
        current.push(character);
    }
    output
}

fn identifiers(source: &str) -> Result<HashSet<String>> {
    let identifier = Regex::new(r"\b[A-Za-z_]\w*\b")?;
    Ok(identifier
        .find_iter(source)
        .map(|found| found.as_str().to_owned())
        .collect())
}

fn declared_names(statement: &str) -> Result<HashSet<String>> {
    let tagged = Regex::new(r"\b(struct|union|enum)\s+([A-Za-z_]\w*)")?;
    let identifier = Regex::new(r"\b[A-Za-z_]\w*\b")?;
    let mut names = HashSet::new();
    let mut body = statement.to_owned();
    if let Some(opening) = body.find('{') {
        let closing = body
            .rfind('}')
            .context("record statement has no closing brace")?;
        let head = &body[..opening];
        if let Some(found) = tagged.captures(head) {
            names.insert(format!("{} {}", &found[1], &found[2]));
        }
        body = format!("{}{}", head, &body[closing + 1..]);
    } else if !body.trim_start().starts_with("typedef") {
        if let Some(found) = tagged.captures(&body) {
            names.insert(format!("{} {}", &found[1], &found[2]));
        }
    }
    if statement.trim_start().starts_with("typedef") {
        let pointer = Regex::new(r"\(\s*\*\s*([A-Za-z_]\w*)\s*\)")?;
        if let Some(found) = pointer.captures(&body) {
            names.insert(found[1].to_owned());
        } else {
            let before_parameters = body.split('(').next().unwrap_or_default();
            if let Some(found) = identifier.find_iter(before_parameters).last() {
                names.insert(found.as_str().to_owned());
            }
        }
    }
    Ok(names)
}

fn referenced_names(statement: &str) -> Result<HashSet<String>> {
    let tagged = Regex::new(r"\b(struct|union|enum)\s+([A-Za-z_]\w*)")?;
    let mut names = identifiers(statement)?;
    for found in tagged.captures_iter(statement) {
        names.insert(format!("{} {}", &found[1], &found[2]));
    }
    Ok(names)
}

fn recover_types(
    rejected: &str,
    already_declared: &HashSet<String>,
    needed: &[String],
) -> Result<String> {
    let ordered: Vec<_> = statements(rejected)
        .into_iter()
        .filter(|statement| !statement.trim_matches([' ', ';']).is_empty())
        .collect();
    let mut provides = HashMap::new();
    for (index, statement) in ordered.iter().enumerate() {
        for name in declared_names(statement)? {
            if !already_declared.contains(&name) {
                provides.entry(name).or_insert(index);
            }
        }
    }
    let mut chosen = BTreeSet::new();
    let mut pending = needed.to_vec();
    while let Some(name) = pending.pop() {
        let Some(index) = provides.get(&name).copied() else {
            continue;
        };
        if !chosen.insert(index) {
            continue;
        }
        pending.extend(
            referenced_names(&ordered[index])?
                .difference(already_declared)
                .cloned(),
        );
    }
    if chosen.is_empty() {
        Ok(String::new())
    } else {
        Ok(chosen
            .into_iter()
            .map(|index| ordered[index].as_str())
            .collect::<Vec<_>>()
            .join("\n")
            + "\n")
    }
}

fn extract_defines(options: &Options<'_>) -> Result<BTreeMap<String, Constant>> {
    let names = macro_names(options)?;
    if names.is_empty() {
        return Ok(BTreeMap::new());
    }
    let limit_flags = error_limit_flags(options.compiler)?;
    let first = evaluate_macros(options, &names, &limit_flags, "tecsFirst", 0)?;
    let second = evaluate_macros(options, &names, &limit_flags, "tecsSecond", 3)?;
    Ok(first
        .into_iter()
        .filter(|(name, value)| second.get(name) == Some(value))
        .collect())
}

fn macro_names(options: &Options<'_>) -> Result<Vec<String>> {
    let output = preprocess(options, true)?;
    let macro_line = Regex::new(r"^#define\s+([A-Za-z_]\w*)\s+(.*)$")?;
    let mut names = BTreeSet::new();
    for line in output.lines() {
        let Some(found) = macro_line.captures(line.trim()) else {
            continue;
        };
        let name = &found[1];
        let body = &found[2];
        if !options.define_prefixes.is_empty()
            && !options
                .define_prefixes
                .iter()
                .any(|prefix| name.starts_with(prefix))
        {
            continue;
        }
        if !body.trim().is_empty() {
            names.insert(name.to_owned());
        }
    }
    Ok(names.into_iter().collect())
}

fn evaluate_macros(
    options: &Options<'_>,
    names: &[String],
    limit_flags: &[String],
    function: &str,
    padding: usize,
) -> Result<BTreeMap<String, Constant>> {
    let mut prologue: Vec<String> = options
        .headers
        .iter()
        .map(|header| format!("#include <{header}>"))
        .collect();
    prologue.extend([
        "#include <stdio.h>".to_owned(),
        "#include <stdint.h>".to_owned(),
        "static void tecsString(const char *name, const char *value) { printf(\"%s\\tS\\t%s\\n\", name, value); }".to_owned(),
        "static void tecsSigned(const char *name, long long value) { printf(\"%s\\tI\\t%lld\\n\", name, value); }".to_owned(),
        "static void tecsUnsigned(const char *name, unsigned long long value) { printf(\"%s\\tU\\t%llu\\n\", name, value); }".to_owned(),
        "static void tecsFloat(const char *name, double value) { printf(\"%s\\tF\\t%.17g\\n\", name, value); }".to_owned(),
        "static void tecsSkip(const char *name, ...) { (void)name; }".to_owned(),
        "#define TECS_PRINT(name, x) _Generic((x) + 0, char *: tecsString, const char *: tecsString, _Bool: tecsSigned, char: tecsSigned, signed char: tecsSigned, short: tecsSigned, int: tecsSigned, long: tecsSigned, long long: tecsSigned, unsigned char: tecsUnsigned, unsigned short: tecsUnsigned, unsigned int: tecsUnsigned, unsigned long: tecsUnsigned, unsigned long long: tecsUnsigned, float: tecsFloat, double: tecsFloat, default: tecsSkip)(name, (x))".to_owned(),
    ]);
    prologue.extend(std::iter::repeat_n(String::new(), padding));
    prologue.push(format!("static void {function}(void) {{"));
    let epilogue = [
        "}".to_owned(),
        "int main(void) {".to_owned(),
        format!("    {function}();"),
        "    return 0;".to_owned(),
        "}".to_owned(),
        String::new(),
    ];
    let mut dropped = HashSet::new();
    let diagnostic = Regex::new(&format!(r"{PROBE_NAME}\.c:(\d+):"))?;
    for _ in 0..40 {
        let active: Vec<_> = names
            .iter()
            .filter(|name| !dropped.contains(name.as_str()))
            .collect();
        if active.is_empty() {
            return Ok(BTreeMap::new());
        }
        let body: Vec<_> = active
            .iter()
            .map(|name| format!("    TECS_PRINT(\"{name}\", {name});"))
            .collect();
        let program = prologue
            .iter()
            .chain(&body)
            .chain(&epilogue)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n");
        let directory = tempdir()?;
        let source = directory.path().join(format!("{PROBE_NAME}.c"));
        let executable = directory.path().join(PROBE_NAME);
        fs::write(&source, program)?;
        let mut command = Command::new(options.compiler);
        command.args(["-std=c11", "-w"]);
        command.args(limit_flags);
        command.arg("-o").arg(&executable).arg(&source);
        add_compiler_options(&mut command, options);
        let build = command
            .output()
            .context("starting constant probe compiler")?;
        if !build.status.success() {
            let errors = String::from_utf8_lossy(&build.stderr);
            let mut bad = HashSet::new();
            for found in diagnostic.captures_iter(&errors) {
                let line: usize = found[1].parse()?;
                let index = line.saturating_sub(prologue.len() + 1);
                if index < active.len() {
                    bad.insert(active[index].as_str());
                }
            }
            if bad.is_empty() {
                anyhow::bail!(
                    "cannot evaluate constants:\n{}",
                    errors.chars().take(2000).collect::<String>()
                );
            }
            dropped.extend(bad.into_iter().map(str::to_owned));
            continue;
        }
        let run = Command::new(&executable)
            .output()
            .context("running constant probe")?;
        if !run.status.success() {
            anyhow::bail!("constant probe exited with {}", run.status);
        }
        let mut found = BTreeMap::new();
        for line in String::from_utf8(run.stdout)?.lines() {
            let mut parts = line.splitn(3, '\t');
            let (Some(name), Some(kind), Some(value)) = (parts.next(), parts.next(), parts.next())
            else {
                continue;
            };
            if kind == "S" {
                if !value.contains(PROBE_NAME) {
                    found.insert(name.to_owned(), Constant::String(value.to_owned()));
                }
            } else if kind == "I" {
                if let Ok(value) = value.parse() {
                    found.insert(name.to_owned(), Constant::Integer(value));
                }
            } else if kind == "U" {
                if let Ok(value) = value.parse() {
                    found.insert(name.to_owned(), Constant::Unsigned(value));
                }
            } else if kind == "F" && value.parse::<f64>().is_ok_and(|number| number.is_finite()) {
                found.insert(name.to_owned(), Constant::Float(value.to_owned()));
            }
        }
        return Ok(found);
    }
    anyhow::bail!("constant extraction did not converge")
}

fn error_limit_flags(compiler: &str) -> Result<Vec<String>> {
    for flag in ["-ferror-limit=0", "-fmax-errors=0"] {
        let directory = tempdir()?;
        let source = directory.path().join("probe.c");
        let executable = directory.path().join("probe");
        fs::write(&source, "int main(void) { return 0; }\n")?;
        if Command::new(compiler)
            .arg(flag)
            .arg("-o")
            .arg(executable)
            .arg(source)
            .status()
            .is_ok_and(|status| status.success())
        {
            return Ok(vec![flag.to_owned()]);
        }
    }
    Ok(Vec::new())
}

fn write(path: &Path, contents: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, contents).with_context(|| format!("writing {}", path.display()))
}

#[cfg(test)]
mod tests {
    use std::fs;

    use regex::Regex;
    use tempfile::tempdir;

    use super::{
        clean, declared_names, extract_defines, statements, strip_balanced, Constant, Options,
    };

    #[test]
    fn strips_nested_attributes() {
        let pattern = Regex::new(r"__attribute__\s*\(").unwrap();
        assert_eq!(
            strip_balanced("int x __attribute__((aligned(sizeof(int))));", &pattern),
            "int x ;"
        );
    }

    #[test]
    fn top_level_statements_ignore_record_members() {
        let found = statements("typedef struct X { int a; int b; } X; int f(void);");
        assert_eq!(found.len(), 2);
    }

    #[test]
    fn finds_typedef_and_tag_names() {
        let names = declared_names("typedef struct Thing { int value; } Alias;").unwrap();
        assert!(names.contains("struct Thing"));
        assert!(names.contains("Alias"));
    }

    #[test]
    fn removes_static_definitions() {
        let result =
            clean("static inline int helper(void) { return 1; }\nextern int api(void);").unwrap();
        assert_eq!(result, "extern int api(void);\n");
    }

    #[test]
    fn renders_integers_without_losing_precision() {
        assert_eq!(Constant::Integer(1_i64 << 54).lua(), "18014398509481984LL");
        assert_eq!(
            Constant::Unsigned(u64::MAX).lua(),
            "18446744073709551615ULL"
        );
        assert_eq!(Constant::Unsigned(42).lua(), "42");
    }

    #[test]
    fn preserves_floating_and_unsigned_macros() {
        let directory = tempdir().unwrap();
        fs::write(
            directory.path().join("constants.h"),
            "#include <stdint.h>\n\
             #define TEST_EPSILON 1.1920928955078125e-7F\n\
             #define TEST_PI 3.14159265358979323846\n\
             #define TEST_GRAVITY 9.80665\n\
             #define TEST_MAX_UINT64 UINT64_MAX\n\
             #define TEST_STRING \"exact string\"\n\
             #define TEST_LONG_DOUBLE 1.0L\n",
        )
        .unwrap();
        let headers = vec!["constants.h".to_owned()];
        let includes = vec![directory.path().to_owned()];
        let prefixes = vec!["TEST_".to_owned()];
        let output = directory.path().join("unused.lua");
        let constants = extract_defines(&Options {
            compiler: "cc",
            headers: &headers,
            include_directories: &includes,
            defines: &[],
            keeps: &[],
            needed: &[],
            define_prefixes: &prefixes,
            constants_output: None,
            output: &output,
        })
        .unwrap();

        for (name, expected) in [
            ("TEST_EPSILON", 1.1920928955078125e-7),
            ("TEST_PI", std::f64::consts::PI),
            ("TEST_GRAVITY", 9.80665),
        ] {
            let Constant::Float(value) = &constants[name] else {
                panic!("{name} was not extracted as a floating-point value");
            };
            assert_eq!(value.parse::<f64>().unwrap(), expected);
        }
        assert_eq!(constants["TEST_MAX_UINT64"], Constant::Unsigned(u64::MAX));
        assert_eq!(
            constants["TEST_STRING"],
            Constant::String("exact string".to_owned())
        );
        assert!(!constants.contains_key("TEST_LONG_DOUBLE"));
    }
}
