use std::collections::{HashMap, HashSet};
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use regex::Regex;
use unicode_normalization::UnicodeNormalization;
use walkdir::WalkDir;

const REFERENCE_MARKER: &str =
    "<!-- @generated by `cargo xtask docs-reference` from {sources}. Do not edit below this line. -->";
const REFERENCE_LEAD: &str =
    "## Reference\n\nEvery function and type this module carries, rendered from {sources}.";

#[derive(Clone, Copy)]
struct ReferenceSource {
    path: &'static str,
    public: &'static str,
}

struct ReferencePage {
    page: &'static str,
    sources: &'static [ReferenceSource],
}

const REFERENCE_PAGES: &[ReferencePage] = &[
    reference(
        "docs/ecs/index.md",
        &[source("src/tecs/ecs.tl", "tecs.ecs")],
    ),
    reference(
        "docs/modules/Application.md",
        &[source("src/tecs/Application.tl", "tecs.Application")],
    ),
    reference(
        "docs/modules/Future.md",
        &[source("src/tecs/Future.tl", "tecs.Future")],
    ),
    reference(
        "docs/modules/assets.md",
        &[source("src/tecs/assets.tl", "tecs.assets")],
    ),
    reference(
        "docs/modules/audio.md",
        &[
            source("src/tecs/audio.tl", "tecs.audio"),
            source("src/tecs/platform/audio.tl", "tecs.audio"),
        ],
    ),
    reference(
        "docs/modules/data.md",
        &[source("src/tecs/data.tl", "tecs.data")],
    ),
    reference(
        "docs/modules/events.md",
        &[source("src/tecs/platform/events.tl", "tecs.events")],
    ),
    reference(
        "docs/modules/filesystem/index.md",
        &[source("src/tecs/platform/filesystem.tl", "tecs.filesystem")],
    ),
    reference(
        "docs/modules/filesystem/watch.md",
        &[source(
            "src/tecs/platform/watch.tl",
            "tecs.filesystem.watch",
        )],
    ),
    reference(
        "docs/modules/gfx/index.md",
        &[
            source("src/tecs/gfx/Camera.tl", "tecs.gfx.Camera"),
            source("src/tecs/components.tl", "tecs.gfx"),
            source("src/tecs/Renderer.tl", "tecs.gfx.Renderer"),
            source("src/tecs/gfx/text.tl", "tecs.gfx"),
        ],
    ),
    reference(
        "docs/modules/gfx/animation.md",
        &[source("src/tecs/gfx/animation.tl", "tecs.gfx.animation")],
    ),
    reference(
        "docs/modules/gfx/layers.md",
        &[source("src/tecs/gfx/layers.tl", "tecs.gfx.layers")],
    ),
    reference(
        "docs/modules/gfx/materials.md",
        &[source("src/tecs/gpu/materials.tl", "tecs.gfx.materials")],
    ),
    reference(
        "docs/modules/gfx/particles.md",
        &[source("src/tecs/gfx/particles.tl", "tecs.gfx.particles")],
    ),
    reference(
        "docs/modules/input.md",
        &[
            source("src/tecs/platform/input.tl", "tecs.input"),
            source("src/tecs/platform/Gamepad.tl", "tecs.input.Gamepad"),
            source("src/tecs/platform/sensors.tl", "tecs.input"),
        ],
    ),
    reference(
        "docs/modules/log.md",
        &[source("src/tecs/log.tl", "tecs.log")],
    ),
    reference(
        "docs/modules/math.md",
        &[source("src/tecs/math.tl", "tecs.math")],
    ),
    reference(
        "docs/modules/mcp.md",
        &[source("src/tecs/mcp/init.tl", "tecs.mcp")],
    ),
    reference(
        "docs/modules/net/index.md",
        &[source("src/tecs/net.tl", "tecs.net")],
    ),
    reference(
        "docs/modules/physics.md",
        &[source("src/tecs/physics/init.tl", "tecs.physics")],
    ),
    reference(
        "docs/modules/sequence.md",
        &[source("src/tecs/sequence/init.tl", "tecs.sequence")],
    ),
    reference(
        "docs/modules/system.md",
        &[source("src/tecs/platform/system.tl", "tecs.system")],
    ),
    reference(
        "docs/modules/time.md",
        &[source("src/tecs/platform/time.tl", "tecs.time")],
    ),
    reference(
        "docs/modules/window.md",
        &[source("src/tecs/platform/window.tl", "tecs.window")],
    ),
    reference(
        "docs/modules/workers.md",
        &[source("src/tecs/workers.tl", "tecs.workers")],
    ),
];

const fn reference(page: &'static str, sources: &'static [ReferenceSource]) -> ReferencePage {
    ReferencePage { page, sources }
}

const fn source(path: &'static str, public: &'static str) -> ReferenceSource {
    ReferenceSource { path, public }
}

#[derive(Debug)]
struct Link {
    line: usize,
    target: String,
}

pub fn check_links(docs: &Path) -> Result<usize> {
    let mut pages: Vec<_> = WalkDir::new(docs)
        .into_iter()
        .filter_entry(|entry| {
            !entry.file_type().is_dir()
                || !matches!(
                    entry.file_name().to_str(),
                    Some(".vitepress" | "node_modules")
                )
        })
        .collect::<Result<Vec<_>, _>>()?
        .into_iter()
        .filter(|entry| {
            entry.file_type().is_file()
                && entry.path().extension().and_then(|value| value.to_str()) == Some("md")
                && !entry.path().components().any(|component| {
                    matches!(
                        component.as_os_str().to_str(),
                        Some(".vitepress" | "node_modules")
                    )
                })
        })
        .map(|entry| entry.into_path())
        .collect();
    pages.sort();
    let design_record = Regex::new(r"README\.md(?:#|$|\?)")?;
    let skipped = ["http://", "https://", "mailto:", "tel:", "//"];
    let mut anchors = HashMap::<PathBuf, HashSet<String>>::new();
    let mut broken = Vec::new();
    let mut total = 0;
    for page in &pages {
        let links = links_in(page)?;
        total += links.len();
        let relative = page.strip_prefix(docs)?;
        for link in links {
            if design_record.is_match(&link.target) {
                broken.push((
                    relative.to_path_buf(),
                    link.line,
                    link.target,
                    "links into the design record",
                ));
                continue;
            }
            if skipped.iter().any(|prefix| link.target.starts_with(prefix)) {
                continue;
            }
            let (route, fragment) = link
                .target
                .split_once('#')
                .map_or((link.target.as_str(), ""), |(route, fragment)| {
                    (route, fragment)
                });
            let destination = if route.is_empty() {
                Some(page.clone())
            } else if route.starts_with('/') {
                page_for(docs, route)?
            } else {
                broken.push((
                    relative.to_path_buf(),
                    link.line,
                    link.target,
                    "relative link",
                ));
                continue;
            };
            let Some(destination) = destination else {
                broken.push((
                    relative.to_path_buf(),
                    link.line,
                    link.target,
                    "no such page",
                ));
                continue;
            };
            if fragment.is_empty() {
                continue;
            }
            if !anchors.contains_key(&destination) {
                anchors.insert(destination.clone(), anchors_of(&destination)?);
            }
            if !anchors[&destination].contains(fragment) {
                broken.push((
                    relative.to_path_buf(),
                    link.line,
                    link.target,
                    "no such anchor",
                ));
            }
        }
    }
    if !broken.is_empty() {
        let details = broken
            .iter()
            .map(|(path, line, target, reason)| {
                format!("  docs/{}:{line}  {target}  ({reason})", path.display())
            })
            .collect::<Vec<_>>()
            .join("\n");
        anyhow::bail!("Broken links: {}\n{details}", broken.len());
    }
    println!("OK: {} pages, {total} links, none broken", pages.len());
    Ok(total)
}

pub fn references(root: &Path, check: bool) -> Result<()> {
    let tealdoc = root.join("vendor/bin/tealdoc");
    if !tealdoc.is_file() {
        anyhow::bail!("tealdoc is not in vendor/bin; run `cargo xtask dev-tools`");
    }
    let directory = tempfile::Builder::new()
        .prefix("tecs-reference.")
        .tempdir()?;
    let mut stale = Vec::new();
    for reference in REFERENCE_PAGES {
        let page = root.join(reference.page);
        let composed =
            compose_reference(root, &tealdoc, &page, reference.sources, directory.path())?;
        if check {
            let candidate = directory.path().join(
                page.file_name()
                    .context("reference page has no file name")?,
            );
            fs::write(&candidate, composed)?;
            prettify(root, &candidate)?;
            if fs::read(&candidate)? != fs::read(&page)? {
                stale.push(reference.page);
            }
        } else {
            fs::write(&page, composed)?;
            prettify(root, &page)?;
        }
    }
    let stray = stray_tags(root)?;
    if !stray.is_empty() {
        anyhow::bail!(
            "Pages Vue will read as having an unclosed element: {}\n{}",
            stray.len(),
            stray
                .iter()
                .map(|(page, line, name, source)| {
                    format!("  {}:{line}  <{name}>  {source}", page.display())
                })
                .collect::<Vec<_>>()
                .join("\n")
        );
    }
    if check && !stale.is_empty() {
        anyhow::bail!(
            "Module pages are stale against their sources:\n{}\n\nRun `cargo xtask docs-reference` to regenerate them.",
            stale
                .iter()
                .map(|page| format!("  {page}"))
                .collect::<Vec<_>>()
                .join("\n")
        );
    }
    if check {
        println!("OK: every module page matches a fresh render, and none has a stray tag");
    } else {
        println!(
            "wrote the reference section of {} pages",
            REFERENCE_PAGES.len()
        );
    }
    Ok(())
}

fn compose_reference(
    root: &Path,
    tealdoc: &Path,
    page: &Path,
    sources: &[ReferenceSource],
    scratch: &Path,
) -> Result<String> {
    let text = fs::read_to_string(page)?;
    let marker = Regex::new(
        r"(?m)^<!-- @generated (?:by docs/scripts/reference\.py|by `cargo xtask docs-reference`) .*-->$",
    )?;
    let prose = marker
        .find(&text)
        .map_or(text.as_str(), |found| &text[..found.start()]);
    let mut items: Vec<(String, String)> = Vec::new();
    let mut positions: HashMap<String, usize> = HashMap::new();
    for source in sources {
        for (name, body) in render_reference(root, tealdoc, *source, scratch)? {
            if let Some(index) = positions.get(&name).copied() {
                items[index].1 = body;
            } else {
                positions.insert(name.clone(), items.len());
                items.push((name, body));
            }
        }
    }
    let paths: Vec<_> = sources.iter().map(|source| source.path).collect();
    let named = sentence(&paths);
    let marker = REFERENCE_MARKER.replace("{sources}", &paths.join(", "));
    let lead = REFERENCE_LEAD.replace("{sources}", &named);
    Ok(format!(
        "{}\n{marker}\n\n{lead}\n\n{}\n",
        prose.trim_end(),
        items
            .into_iter()
            .map(|(_, body)| body)
            .collect::<Vec<_>>()
            .join("\n\n")
    ))
}

fn render_reference(
    root: &Path,
    tealdoc: &Path,
    source: ReferenceSource,
    scratch: &Path,
) -> Result<Vec<(String, String)>> {
    let raw = scratch.join("raw.md");
    let status = std::process::Command::new(tealdoc)
        .args(["md", "--no-warn-missing", "-o"])
        .arg(&raw)
        .arg(source.path)
        .current_dir(root)
        .status()
        .context("running tealdoc")?;
    if !status.success() {
        anyhow::bail!("tealdoc exited with {status} for {}", source.path);
    }
    let module = module_name(source.path);
    let anchor = Regex::new(r#"^<a id="(.+)"></a>$"#)?;
    let mut blocks: Vec<(String, Vec<String>)> = Vec::new();
    let mut name = String::new();
    let mut current = Vec::new();
    for line in fs::read_to_string(raw)?.lines() {
        if let Some(found) = anchor.captures(line) {
            if !current.is_empty() {
                blocks.push((std::mem::take(&mut name), std::mem::take(&mut current)));
            }
            name = found[1].to_owned();
            current.push(line.to_owned());
        } else if !current.is_empty() {
            current.push(line.to_owned());
        }
    }
    if !current.is_empty() {
        blocks.push((name, current));
    }
    let heading = Regex::new(r"(?m)^## ")?;
    let mut kept = Vec::new();
    for (name, block) in blocks {
        if name == module || name == format!("${module}") {
            continue;
        }
        let member = name.strip_prefix(&(module.clone() + ".")).unwrap_or(&name);
        if member.split('.').any(|part| part.starts_with('_')) {
            continue;
        }
        let mut body = block.join("\n");
        body = body.replace(&(module.clone() + "."), &(source.public.to_owned() + "."));
        body = heading.replace_all(&body, "### ").into_owned();
        body = body
            .lines()
            .map(escape_braces)
            .collect::<Vec<_>>()
            .join("\n");
        let public_name = name.replacen(
            &(module.clone() + "."),
            &(source.public.to_owned() + "."),
            1,
        );
        kept.push((public_name, body.trim_matches('\n').to_owned()));
    }
    Ok(kept)
}

fn module_name(source: &str) -> String {
    source
        .strip_prefix("src/")
        .unwrap_or(source)
        .strip_suffix(".tl")
        .unwrap_or(source)
        .replace('/', ".")
}

fn escape_braces(line: &str) -> String {
    let mut output = String::new();
    let mut code = false;
    let mut characters = line.chars().peekable();
    while let Some(character) = characters.next() {
        if character == '`' {
            code = !code;
            output.push(character);
        } else if !code && character == '{' && characters.peek() == Some(&'{') {
            characters.next();
            output.push_str("<span v-pre>{{</span>");
        } else {
            output.push(character);
        }
    }
    output
}

fn sentence(sources: &[&str]) -> String {
    let quoted: Vec<_> = sources.iter().map(|source| format!("`{source}`")).collect();
    match quoted.as_slice() {
        [] => String::new(),
        [only] => only.clone(),
        [head @ .., last] => format!("{} and {last}", head.join(", ")),
    }
}

fn prettify(root: &Path, path: &Path) -> Result<()> {
    let status = std::process::Command::new("prettier")
        .args(["--write", "--log-level", "warn", "--config"])
        .arg(root.join(".prettierrc"))
        .arg(path)
        .current_dir(root)
        .status()
        .context("running prettier")?;
    if !status.success() {
        anyhow::bail!("prettier exited with {status}");
    }
    Ok(())
}

fn stray_tags(root: &Path) -> Result<Vec<(PathBuf, usize, String, String)>> {
    let allowed: HashSet<_> = [
        "a", "b", "br", "code", "div", "em", "hr", "i", "img", "li", "ol", "p", "pre", "script",
        "span", "strong", "style", "sub", "sup", "table", "tbody", "td", "th", "thead", "tr", "ul",
    ]
    .into_iter()
    .collect();
    let tag = Regex::new(r"<(/?)([A-Za-z][A-Za-z0-9_]*)")?;
    let code = Regex::new(r"`[^`]*`")?;
    let docs = root.join("docs");
    let mut findings = Vec::new();
    for entry in WalkDir::new(&docs).into_iter().filter_entry(|entry| {
        !entry.file_type().is_dir()
            || !matches!(
                entry.file_name().to_str(),
                Some(".vitepress" | "node_modules")
            )
    }) {
        let entry = entry?;
        if !entry.file_type().is_file()
            || entry.path().extension().and_then(|value| value.to_str()) != Some("md")
            || entry.path().components().any(|component| {
                matches!(
                    component.as_os_str().to_str(),
                    Some(".vitepress" | "node_modules")
                )
            })
        {
            continue;
        }
        let mut fenced = false;
        for (index, line) in fs::read_to_string(entry.path())?.lines().enumerate() {
            if line.trim_start().starts_with("```") {
                fenced = !fenced;
                continue;
            }
            if fenced || line.starts_with("    ") {
                continue;
            }
            let prose = code.replace_all(line, "");
            for found in tag.captures_iter(&prose) {
                let name = found[2].to_owned();
                if !allowed.contains(name.to_lowercase().as_str()) {
                    findings.push((
                        entry.path().strip_prefix(root)?.to_path_buf(),
                        index + 1,
                        name,
                        line.trim().to_owned(),
                    ));
                }
            }
        }
    }
    Ok(findings)
}

fn links_in(path: &Path) -> Result<Vec<Link>> {
    let markdown = Regex::new(r"\[[^\]]*\]\(([^)\s]+)\)")?;
    let html = Regex::new(r#"href="([^"]+)""#)?;
    let source = fs::read_to_string(path)?;
    let mut links = Vec::new();
    let mut fenced = false;
    for (index, line) in source.lines().enumerate() {
        if line.starts_with("```") {
            fenced = !fenced;
            continue;
        }
        if fenced {
            continue;
        }
        for found in markdown.captures_iter(line).chain(html.captures_iter(line)) {
            links.push(Link {
                line: index + 1,
                target: found[1].to_owned(),
            });
        }
    }
    Ok(links)
}

fn anchors_of(path: &Path) -> Result<HashSet<String>> {
    let html = Regex::new(r#"<a id="([^"]+)""#)?;
    let heading = Regex::new(r"^(#{1,6})\s+(.*?)\s*$")?;
    let explicit = Regex::new(r"\{#([^}]+)\}\s*$")?;
    let source = fs::read_to_string(path)?;
    let mut anchors = HashSet::new();
    let mut fenced = false;
    for line in source.lines() {
        if line.starts_with("```") {
            fenced = !fenced;
            continue;
        }
        if fenced {
            continue;
        }
        anchors.extend(html.captures_iter(line).map(|found| found[1].to_owned()));
        let Some(found) = heading.captures(line) else {
            continue;
        };
        if let Some(id) = explicit.captures(&found[2]) {
            anchors.insert(id[1].to_owned());
        } else {
            anchors.insert(slug(&found[2])?);
        }
    }
    Ok(anchors)
}

fn slug(source: &str) -> Result<String> {
    let explicit = Regex::new(r"\{#[^}]+\}\s*$")?;
    let code = Regex::new(r"`([^`]*)`")?;
    let link = Regex::new(r"\[([^\]]*)\]\([^)]*\)")?;
    let emphasis = Regex::new(r"[*_]{1,3}([^*_]*)[*_]{1,3}")?;
    let mut text = explicit.replace(source, "").into_owned();
    text = code.replace_all(&text, "$1").into_owned();
    text = link.replace_all(&text, "$1").into_owned();
    text = emphasis.replace_all(&text, "$1").into_owned();
    text = text
        .nfkd()
        .filter(|character| character.is_alphanumeric() || matches!(character, '_' | '-' | ' '))
        .collect::<String>()
        .to_lowercase();
    Ok(text.trim().replace(' ', "-"))
}

fn page_for(docs: &Path, route: &str) -> Result<Option<PathBuf>> {
    let clean = route.trim_matches('/');
    let candidate = if clean.is_empty() {
        docs.join("index.md")
    } else if route.ends_with('/') {
        docs.join(clean).join("index.md")
    } else {
        docs.join(format!("{clean}.md"))
    };
    if exact_file(docs, &candidate)? {
        Ok(Some(candidate))
    } else {
        Ok(None)
    }
}

fn exact_file(docs: &Path, path: &Path) -> Result<bool> {
    if !path.is_file() {
        return Ok(false);
    }
    let mut walked = docs.to_path_buf();
    for component in path.strip_prefix(docs)?.components() {
        let name = component.as_os_str();
        let names = fs::read_dir(&walked)?
            .collect::<Result<Vec<_>, _>>()?
            .into_iter()
            .map(|entry| entry.file_name())
            .collect::<HashSet<_>>();
        if !names.contains(name) {
            return Ok(false);
        }
        walked.push(name);
    }
    Ok(true)
}

pub fn check_descriptions(root: &Path) -> Result<()> {
    let script = root.join("scripts/check-docs-descriptions.sh");
    let status = std::process::Command::new("bash")
        .arg(&script)
        .current_dir(root)
        .status()
        .with_context(|| format!("running {}", script.display()))?;
    if !status.success() {
        anyhow::bail!("documentation description check exited with {status}");
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::slug;

    #[test]
    fn vitepress_slug_removes_markup_and_punctuation() {
        assert_eq!(
            slug("The **GPU** and `tecs.gfx`!").unwrap(),
            "the-gpu-and-tecsgfx"
        );
    }

    #[test]
    fn vitepress_slug_honors_unicode_words() {
        assert_eq!(slug("Café déjà vu").unwrap(), "cafe-deja-vu");
    }
}
