use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::Path;
use std::process::Command;

use anyhow::{Context, Result};
use serde::Serialize;

use crate::command;

const EXCLUDED: &[&str] = &["vendor/", "assets/fonts/"];
const GENERATED_MARKERS: &[&str] = &["generated by", "@generated", "do not edit"];
const GENERATED_SCAN_LINES: usize = 5;

#[derive(Clone, Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct FormatDescription {
    excluded: Vec<String>,
    generated_markers: Vec<String>,
    generated_scan_lines: usize,
    suffixes: BTreeMap<String, String>,
    names: BTreeMap<String, String>,
    tools: BTreeMap<String, Tool>,
}

#[derive(Clone, Debug, Serialize)]
pub struct Tool {
    tool: String,
    apply: Vec<String>,
    check: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    module: Option<String>,
}

pub fn description() -> FormatDescription {
    let suffixes = [
        (".c", "c"),
        (".h", "c"),
        (".lua", "lua"),
        (".tl", "teal"),
        (".json", "prettier"),
        (".jsonc", "prettier"),
        (".js", "prettier"),
        (".jsx", "prettier"),
        (".mjs", "prettier"),
        (".cjs", "prettier"),
        (".ts", "prettier"),
        (".tsx", "prettier"),
        (".mts", "prettier"),
        (".cts", "prettier"),
        (".vue", "prettier"),
        (".css", "prettier"),
        (".scss", "prettier"),
        (".html", "prettier"),
        (".md", "prettier"),
        (".yml", "prettier"),
        (".yaml", "prettier"),
    ]
    .into_iter()
    .map(|(suffix, language)| (suffix.to_owned(), language.to_owned()))
    .collect();
    let tools = [
        (
            "c",
            tool(
                "clang-format",
                &["clang-format", "-i"],
                &["clang-format", "--dry-run", "--Werror"],
                None,
            ),
        ),
        (
            "lua",
            tool("stylua", &["stylua"], &["stylua", "--check"], None),
        ),
        (
            "teal",
            tool(
                "vendor/bin/ceru",
                &["vendor/bin/ceru"],
                &["vendor/bin/ceru", "--check"],
                Some("cerulean.cli"),
            ),
        ),
        (
            "prettier",
            tool(
                "prettier",
                &["prettier", "--write", "--log-level", "warn"],
                &["prettier", "--check", "--log-level", "warn"],
                None,
            ),
        ),
    ]
    .into_iter()
    .map(|(language, spec)| (language.to_owned(), spec))
    .collect();
    FormatDescription {
        excluded: EXCLUDED.iter().map(|value| (*value).to_owned()).collect(),
        generated_markers: GENERATED_MARKERS
            .iter()
            .map(|value| (*value).to_owned())
            .collect(),
        generated_scan_lines: GENERATED_SCAN_LINES,
        suffixes,
        names: BTreeMap::new(),
        tools,
    }
}

fn tool(program: &str, apply: &[&str], check: &[&str], module: Option<&str>) -> Tool {
    Tool {
        tool: program.to_owned(),
        apply: apply.iter().map(|value| (*value).to_owned()).collect(),
        check: check.iter().map(|value| (*value).to_owned()).collect(),
        module: module.map(str::to_owned),
    }
}

pub fn apply(root: &Path, paths: &[String], check: bool) -> Result<()> {
    let cargo_args = if check {
        ["fmt", "--all", "--", "--check"].as_slice()
    } else {
        ["fmt", "--all"].as_slice()
    };
    command::run("cargo", cargo_args, root)?;

    let description = description();
    let grouped = collect(root, paths, &description)?;
    let mut missing = BTreeSet::new();
    let mut failed = Vec::new();
    for (language, files) in grouped {
        let spec = description
            .tools
            .get(&language)
            .with_context(|| format!("no formatter is configured for {language}"))?;
        if !on_path(root, &spec.tool) {
            missing.insert(spec.tool.clone());
            continue;
        }
        let mut arguments = if check {
            spec.check.clone()
        } else {
            spec.apply.clone()
        };
        let program = arguments.remove(0);
        arguments.extend(files);
        if command::run(&program, &arguments, root).is_err() {
            failed.push(language);
        }
    }
    if !missing.is_empty() {
        anyhow::bail!(
            "formatters not installed: {}. Run `cargo xtask deps`.",
            missing.into_iter().collect::<Vec<_>>().join(", ")
        );
    }
    if !failed.is_empty() {
        anyhow::bail!(
            "{}: {}",
            if check {
                "not formatted"
            } else {
                "failed to format"
            },
            failed.join(", ")
        );
    }
    Ok(())
}

fn collect(
    root: &Path,
    paths: &[String],
    description: &FormatDescription,
) -> Result<BTreeMap<String, Vec<String>>> {
    let mut command = Command::new("git");
    command.args(["-C"]).arg(root).args([
        "ls-files",
        "-z",
        // Tracked files and the untracked ones that are not ignored. Without
        // `--others` a file that has never been committed is invisible here, so
        // a check over it passes by finding nothing, which reads as formatted
        // and is the opposite of what it means. A new file is exactly the one
        // most likely to need formatting.
        "--cached",
        "--others",
        "--exclude-standard",
        "--",
    ]);
    command.args(paths);
    let output = command.output().context("running git ls-files")?;
    if !output.status.success() {
        anyhow::bail!("git ls-files exited with {}", output.status);
    }
    let mut grouped: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for bytes in output.stdout.split(|byte| *byte == 0) {
        if bytes.is_empty() {
            continue;
        }
        let name = String::from_utf8(bytes.to_vec()).context("git returned a non-UTF-8 path")?;
        if description
            .excluded
            .iter()
            .any(|prefix| name.starts_with(prefix))
        {
            continue;
        }
        let path = root.join(&name);
        if !path.is_file() || is_generated(&path)? {
            continue;
        }
        let language = path
            .file_name()
            .and_then(|value| value.to_str())
            .and_then(|filename| description.names.get(filename))
            .or_else(|| {
                path.extension()
                    .and_then(|value| value.to_str())
                    .and_then(|extension| description.suffixes.get(&format!(".{extension}")))
            });
        if let Some(language) = language {
            grouped.entry(language.clone()).or_default().push(name);
        }
    }
    for files in grouped.values_mut() {
        files.sort();
    }
    Ok(grouped)
}

fn is_generated(path: &Path) -> Result<bool> {
    let source = fs::read_to_string(path).unwrap_or_default();
    Ok(source.lines().take(GENERATED_SCAN_LINES).any(|line| {
        let lowered = line.to_lowercase();
        GENERATED_MARKERS
            .iter()
            .any(|marker| lowered.contains(marker))
    }))
}

fn on_path(root: &Path, program: &str) -> bool {
    if program.contains('/') {
        return root.join(program).is_file();
    }
    Command::new(program).arg("--version").output().is_ok()
}
