use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use flate2::write::ZlibEncoder;
use flate2::Compression;
use sha2::{Digest, Sha256};
use walkdir::WalkDir;

const MAGIC: &[u8; 8] = b"TECSPAY1";
const SKIP_SUFFIXES: &[&str] = &[".o", ".obj", ".d", ".pyc"];
const SKIP_NAMES: &[&str] = &[".DS_Store"];

#[derive(Clone, Debug)]
pub struct Root {
    pub prefix: String,
    pub directory: PathBuf,
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct Entry {
    name: String,
    data: Vec<u8>,
}

pub fn generate(roots: &[Root], output: &Path) -> Result<()> {
    let entries = collect(roots)?;
    let plain = pack(&entries)?;
    let identity = format!("{:x}", Sha256::digest(&plain));
    let identity = &identity[..16];
    let mut encoder = ZlibEncoder::new(Vec::new(), Compression::best());
    encoder.write_all(&plain)?;
    let compressed = encoder.finish()?;
    let source = render(&compressed, plain.len(), identity);
    if let Some(parent) = output.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(output, source).with_context(|| format!("writing {}", output.display()))?;
    println!(
        "payload: {} files, {:.2} MB deflated to {:.2} MB ({identity})",
        entries.len(),
        plain.len() as f64 / 1_048_576.0,
        compressed.len() as f64 / 1_048_576.0
    );
    Ok(())
}

fn collect(roots: &[Root]) -> Result<Vec<Entry>> {
    let mut entries = Vec::new();
    for root in roots {
        if !root.directory.is_dir() {
            anyhow::bail!(
                "tecs: {} is not there, so it cannot be packed",
                root.directory.display()
            );
        }
        let mut paths: Vec<_> = WalkDir::new(&root.directory)
            .into_iter()
            .collect::<Result<Vec<_>, _>>()?
            .into_iter()
            .filter(|entry| entry.file_type().is_file())
            .map(|entry| entry.into_path())
            .collect();
        paths.sort();
        for path in paths {
            let filename = path
                .file_name()
                .and_then(|value| value.to_str())
                .unwrap_or_default();
            if SKIP_NAMES.contains(&filename)
                || SKIP_SUFFIXES
                    .iter()
                    .any(|suffix| filename.ends_with(suffix))
            {
                continue;
            }
            let relative = path
                .strip_prefix(&root.directory)?
                .to_string_lossy()
                .replace('\\', "/");
            let name = if root.prefix.is_empty() {
                relative
            } else {
                format!("{}/{relative}", root.prefix)
            };
            entries.push(Entry {
                name,
                data: fs::read(&path).with_context(|| format!("reading {}", path.display()))?,
            });
        }
    }
    Ok(entries)
}

fn pack(entries: &[Entry]) -> Result<Vec<u8>> {
    let count = u32::try_from(entries.len()).context("too many payload entries")?;
    let mut output = Vec::new();
    output.extend_from_slice(MAGIC);
    output.extend_from_slice(&count.to_le_bytes());
    for entry in entries {
        let name = entry.name.as_bytes();
        let name_length = u16::try_from(name.len())
            .with_context(|| format!("payload name is too long: {}", entry.name))?;
        let data_length = u32::try_from(entry.data.len())
            .with_context(|| format!("payload entry is too large: {}", entry.name))?;
        output.extend_from_slice(&name_length.to_le_bytes());
        output.extend_from_slice(name);
        output.extend_from_slice(&data_length.to_le_bytes());
        output.extend_from_slice(&entry.data);
    }
    Ok(output)
}

fn render(compressed: &[u8], plain_length: usize, identity: &str) -> String {
    let mut output = format!(
        "/* Generated by `cargo xtask`. Do not edit.\n\
         *\n\
         * The whole content root, deflated. Rust inflates it once at\n\
         * startup and hands it to Lua, which writes it out beside the cache\n\
         * directory named after the identity below.\n\
         */\n\n\
         #include <stddef.h>\n\n\
         const char tecsPayloadIdentity[] = \"{identity}\";\n\
         const size_t tecsPayloadPlainSize = {plain_length}u;\n\
         const size_t tecsPayloadSize = {}u;\n\
         const unsigned char tecsPayload[] = {{\n",
        compressed.len()
    );
    for chunk in compressed.chunks(20) {
        output.push_str("    ");
        for byte in chunk {
            output.push_str(&format!("0x{byte:02x},"));
        }
        output.push('\n');
    }
    output.push_str("};\n");
    output
}

#[cfg(test)]
mod tests {
    use super::{pack, Entry, MAGIC};

    #[test]
    fn archive_format_is_little_endian_and_stable() {
        let packed = pack(&[Entry {
            name: "lua/a.lua".into(),
            data: b"return 1".to_vec(),
        }])
        .unwrap();
        assert_eq!(&packed[..8], MAGIC);
        assert_eq!(&packed[8..12], &[1, 0, 0, 0]);
        assert_eq!(&packed[12..14], &[9, 0]);
        assert_eq!(&packed[14..23], b"lua/a.lua");
        assert_eq!(&packed[23..27], &[8, 0, 0, 0]);
        assert_eq!(&packed[27..], b"return 1");
    }
}
