use std::collections::HashSet;
use std::fs;
use std::path::Path;

use anyhow::{Context, Result};
use regex::Regex;

#[derive(Clone, Debug)]
struct Function {
    return_type: String,
    name: String,
    parameters: String,
}

pub struct Options<'a> {
    pub cdef: &'a Path,
    pub name: &'a str,
    pub struct_name: &'a str,
    pub prefix: &'a str,
    pub headers: &'a [String],
    pub source_output: &'a Path,
    pub cdef_output: &'a Path,
}

pub fn generate(options: &Options<'_>) -> Result<usize> {
    let cdef = read_cdef(options.cdef)?;
    let functions = declarations(&cdef, options.prefix)?;
    if functions.is_empty() {
        anyhow::bail!("no exported functions found for {}", options.name);
    }
    let body = functions
        .iter()
        .map(|function| {
            format!(
                "    {} (*{})({});",
                function.return_type, function.name, function.parameters
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    let initializers = functions
        .iter()
        .map(|function| format!("    .{} = {},", function.name, function.name))
        .collect::<Vec<_>>()
        .join("\n");
    let headers = options
        .headers
        .iter()
        .map(|header| format!("#include <{header}>"))
        .collect::<Vec<_>>()
        .join("\n");
    let source = format!(
        "/* Generated by `cargo xtask`. Do not edit. */\n\n\
         {headers}\n\n\
         typedef struct {struct_name} {{\n{body}\n}} {struct_name};\n\n\
         static const {struct_name} api = {{\n{initializers}\n}};\n\n\
         const void *tecs_{name}_api(void);\n\n\
         const void *tecs_{name}_api(void)\n{{\n    return &api;\n}}\n",
        struct_name = options.struct_name,
        name = options.name,
    );
    let lua = format!(
        "-- Generated by `cargo xtask`. Do not edit.\n\
         -- Function-pointer table for {}, filled at build time.\n\
         return [==========[\n\
         typedef struct {} {{\n{}\n}} {};\n\
         ]==========]\n",
        options.name, options.struct_name, body, options.struct_name
    );
    write(options.source_output, &source)?;
    write(options.cdef_output, &lua)?;
    println!(
        "{}: {} functions",
        options.source_output.display(),
        functions.len()
    );
    Ok(functions.len())
}

fn read_cdef(path: &Path) -> Result<String> {
    let text = fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;
    let start_marker = "[==========[";
    let end_marker = "]==========]";
    let start = text
        .find(start_marker)
        .context("cdef has no long-bracket opening")?
        + start_marker.len();
    let end = text
        .rfind(end_marker)
        .context("cdef has no long-bracket closing")?;
    Ok(text[start..end].to_owned())
}

fn declarations(cdef: &str, prefix: &str) -> Result<Vec<Function>> {
    let signature = Regex::new(r"(?s)^(.*?)(\b\w+)\s*\((.*)\)$")?;
    let mut seen = HashSet::new();
    let mut functions = Vec::new();
    for statement in statements(cdef) {
        let mut body = statement.split_whitespace().collect::<Vec<_>>().join(" ");
        if body.is_empty()
            || [
                "typedef",
                "struct",
                "union",
                "enum",
                "static",
                "extern \"C\"",
            ]
            .iter()
            .any(|word| body.starts_with(word))
        {
            continue;
        }
        if let Some(value) = body.strip_prefix("extern ") {
            body = value.trim().to_owned();
        }
        let Some(parts) = signature.captures(&body) else {
            continue;
        };
        let return_type = parts[1].trim();
        let name = parts[2].trim();
        let parameters = parts[3].trim();
        if (!prefix.is_empty() && !name.starts_with(prefix))
            || seen.contains(name)
            || return_type.contains("(*")
            || return_type.contains('(')
            || return_type.is_empty()
            || !is_identifier(name)
        {
            continue;
        }
        seen.insert(name.to_owned());
        functions.push(Function {
            return_type: return_type.to_owned(),
            name: name.to_owned(),
            parameters: parameters.to_owned(),
        });
    }
    Ok(functions)
}

fn statements(source: &str) -> Vec<String> {
    let mut depth = 0_i32;
    let mut current = String::new();
    let mut output = Vec::new();
    for character in source.chars() {
        match character {
            '{' => depth += 1,
            '}' => depth -= 1,
            ';' if depth == 0 => {
                output.push(std::mem::take(&mut current));
                continue;
            }
            _ => {}
        }
        current.push(character);
    }
    output
}

fn is_identifier(value: &str) -> bool {
    let mut characters = value.chars();
    matches!(characters.next(), Some(first) if first == '_' || first.is_ascii_alphabetic())
        && characters.all(|character| character == '_' || character.is_ascii_alphanumeric())
}

fn write(path: &Path, contents: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, contents).with_context(|| format!("writing {}", path.display()))
}

#[cfg(test)]
mod tests {
    use super::declarations;

    #[test]
    fn extracts_only_prefixed_functions() {
        let functions = declarations(
            "typedef struct X { int x; } X; extern int SDL_Init(int flags); int other(void);",
            "SDL_",
        )
        .unwrap();
        assert_eq!(functions.len(), 1);
        assert_eq!(functions[0].name, "SDL_Init");
        assert_eq!(functions[0].return_type, "int");
        assert_eq!(functions[0].parameters, "int flags");
    }
}
