use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use anyhow::{Context, Result};
use serde_json::{json, Value};

use crate::formatting;

pub fn generate(teal: &str, cerulean: &str, output: &Path) -> Result<()> {
    let value = json!({
        "format": formatting::description(),
        "pins": {
            "teal": teal,
            "cerulean": cerulean,
        },
    });
    let body = format!(
        "-- Generated by `cargo xtask`. Do not edit.\n\
         --\n\
         -- The formatting table and tool revisions come from the Cargo-owned\n\
         -- build configuration.\n\
         return {}\n",
        render(&value, 0)?
    );
    if let Some(parent) = output.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(output, body).with_context(|| format!("writing {}", output.display()))
}

fn render(value: &Value, indent: usize) -> Result<String> {
    let padding = "    ".repeat(indent);
    let inner = "    ".repeat(indent + 1);
    Ok(match value {
        Value::Null => "nil".to_owned(),
        Value::Bool(value) => value.to_string(),
        Value::Number(value) => value.to_string(),
        Value::String(value) => quote(value),
        Value::Array(values) if values.is_empty() => "{}".to_owned(),
        Value::Array(values) => {
            let rows = values
                .iter()
                .map(|value| Ok(format!("{inner}{}", render(value, indent + 1)?)))
                .collect::<Result<Vec<_>>>()?;
            format!("{{\n{},\n{padding}}}", rows.join(",\n"))
        }
        Value::Object(values) if values.is_empty() => "{}".to_owned(),
        Value::Object(values) => {
            let sorted: BTreeMap<_, _> = values.iter().collect();
            let rows = sorted
                .into_iter()
                .filter(|(_, value)| !value.is_null())
                .map(|(key, value)| {
                    Ok(format!(
                        "{inner}[{}] = {}",
                        quote(key),
                        render(value, indent + 1)?
                    ))
                })
                .collect::<Result<Vec<_>>>()?;
            format!("{{\n{},\n{padding}}}", rows.join(",\n"))
        }
    })
}

fn quote(value: &str) -> String {
    format!(
        "\"{}\"",
        value
            .replace('\\', "\\\\")
            .replace('"', "\\\"")
            .replace('\n', "\\n")
    )
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::render;

    #[test]
    fn renders_sorted_lua_tables() {
        assert_eq!(
            render(&json!({"z": true, "a": ["x"]}), 0).unwrap(),
            "{\n    [\"a\"] = {\n        \"x\",\n    },\n    [\"z\"] = true,\n}"
        );
    }
}
